// @Data composes @Getter + @Setter + @ToString + a required-args constructor
// over the final fields. equals/hashCode are NOT generated by Lombok — they are
// produced by the downstream StructuralEqualitySynthesis pass, which this test
// proves by comparing two structurally-equal instances.
@Data
class Pair {
    private final int a;
    private final int b;
}

Pair p1 = new Pair(1, 2);
Pair p2 = new Pair(1, 2);
Pair p3 = new Pair(1, 9);
print(p1.equals(p2));
print(p1.equals(p3));
print(p1.getA());
print(p1.toString());
