#pragma once

#include "../base/OptimizationPass.hpp"
#include "../../ast/NodeClassesDeclaration.hpp"
#include "lombok/LombokPolicy.hpp"
#include <cstddef>
#include <memory>
#include <string>
#include <unordered_set>
#include <vector>

namespace optimizer::passes
{
    /**
     * Lombok Synthesis Pass — auto-generates boilerplate members from marker
     * annotations, mirroring the StructuralEqualitySynthesisPass (MYT-274)
     * mechanism: it injects synthesized MethodNode/ConstructorNode/ClassNode
     * AST into the program before bytecode compilation, so class registration
     * and the type checker see them as ordinary members.
     *
     * Handled annotations:
     *   @Getter / @Setter         — per-field accessors
     *   @ToString                 — structural toString over inherited + own fields
     *   @NoArgsConstructor        — empty constructor (with super() if parented)
     *   @AllArgsConstructor       — all-fields constructor, parent fields via super(...)
     *   @Data                     — getters + setters + toString + required-args ctor;
     *                               equals/hashCode are left to StructuralEqualitySynthesis
     *   @EqualsAndHashCode        — marker only (delegated to StructuralEqualitySynthesis)
     *   @Builder                  — companion <Class>Builder + static builder()
     *
     * Runs BEFORE StructuralEqualitySynthesis so @Data/@EqualsAndHashCode get
     * their equals/hashCode generated by that downstream pass. Idempotent under
     * the optimizer's fixed-point loop: every emission is guarded by an
     * existence check (member name/arity or constructor signature).
     *
     * Skip rules and field collection live in lombok::LombokPolicy; member
     * construction in lombok::LombokCodegen and lombok::LombokBuilderCodegen.
     */
    class LombokSynthesisPass : public base::OptimizationPass
    {
    private:
        size_t methodsSynthesized = 0;
        size_t constructorsSynthesized = 0;
        size_t builderClassesSynthesized = 0;

        // Processes one class, mutating it in place. Builder companion classes
        // are appended to `newClasses` (deferred to after the program-statement
        // walk to avoid invalidating the iterator); `queuedBuilders` tracks the
        // names queued this run so the same builder isn't emitted twice.
        void processClass(
            ast::ClassNode* classNode,
            const lombok::ClassRegistry& registry,
            std::vector<std::unique_ptr<ast::ASTNode>>& newClasses,
            std::unordered_set<std::string>& queuedBuilders);

    public:
        LombokSynthesisPass();

        std::unique_ptr<ast::ASTNode> optimize(
            std::unique_ptr<ast::ASTNode> node,
            base::OptimizationContext& context) override;

        std::string getDescription() const override;
        void reportMetrics(OptimizationResult& result) const override;
        void reset() override;
    };
}
