#pragma once
#include "ValueType.hpp"
#include "../runtimeTypes/global/VariableDefinition.hpp"
#include <string>
#include <memory>
#include <variant>

namespace value
{
    /**
     * @brief Captured variable representation for lambda closures with memory optimization
     *
     * Stores a variable captured by a lambda, using either:
     * - Value capture: For small primitives and short strings (copy by value)
     * - Reference capture: For large objects (weak_ptr to original VariableDefinition)
     *
     * Design principles:
     * - Hybrid capture strategy for optimal memory usage
     * - std::variant-based storage for type safety and automatic lifetime management
     * - Modern C++17 variant replaces manual union management
     * - Weak references prevent dangling pointers and memory leaks
     *
     * Memory layout:
     * - name: ~32 bytes (std::string)
     * - originalType: 4 bytes (enum)
     * - storage variant: 48 bytes (max of Value vs weak_ptr sizes) + 8 bytes (discriminator)
     * Total: ~92 bytes per captured variable (4 bytes more than union, but safer)
     *
     * Performance characteristics:
     * - getValue(): O(1) for value capture, O(1) + lock overhead for reference
     * - Copy: Deep copy for value capture, weak_ptr copy for reference
     * - Move: Automatic move semantics via std::variant
     *
     * Safety improvements over union version:
     * - No manual lifetime management (std::variant handles construction/destruction)
     * - Type-safe access via std::get<T> and std::holds_alternative<T>
     * - Automatic copy/move semantics
     * - Compile-time type checking
     * - Reference captures can become invalid if original variable destroyed
     * - getValue() returns monostate{} for expired references
     */
    struct CapturedVariable
    {
        std::string name;
        ValueType originalType;

        /**
         * @brief Variant storage for either value or reference
         *
         * Automatically manages lifetime and provides type-safe access.
         * Index 0: Value (by-value capture)
         * Index 1: weak_ptr (by-reference capture)
         */
        std::variant<Value, std::weak_ptr<runtimeTypes::global::VariableDefinition>> storage;

        /**
         * @brief Constructor for value-based capture (small objects)
         *
         * Stores value directly in variant (no manual construction needed).
         * Recommended for primitives, short strings, and small objects (<= 256 bytes).
         *
         * @param n Variable name
         * @param v Value to capture (copied)
         * @param t Original ValueType
         */
        CapturedVariable(const std::string& n, const Value& v, ValueType t)
            : name(n), originalType(t), storage(v) {}

        /**
         * @brief Constructor for reference-based capture (large objects)
         *
         * Stores weak_ptr in variant (no manual construction needed).
         * Recommended for large objects (> 256 bytes) to save memory.
         *
         * @param n Variable name
         * @param ref Weak pointer to original VariableDefinition
         * @param t Original ValueType
         */
        CapturedVariable(const std::string& n, std::weak_ptr<runtimeTypes::global::VariableDefinition> ref, ValueType t)
            : name(n), originalType(t), storage(std::move(ref)) {}

        /**
         * @brief Check if this is a value capture (vs reference capture)
         */
        bool isCapturedByValue() const {
            return std::holds_alternative<Value>(storage);
        }

        /**
         * @brief Get the current value based on capture strategy
         *
         * For value capture: Returns stored value (O(1), always valid)
         * For reference capture: Locks weak_ptr and retrieves current value from VariableDefinition
         *
         * @return Current value, or monostate{} if reference expired
         */
        Value getValue() const {
            if (std::holds_alternative<Value>(storage)) {
                // Value capture - return copy of stored value
                return std::get<Value>(storage);
            } else {
                // Reference capture - get current value from variable
                const auto& weakRef = std::get<std::weak_ptr<runtimeTypes::global::VariableDefinition>>(storage);
                if (auto varDef = weakRef.lock()) {
                    return varDef->getValue();
                }
                // Reference expired - return default value
                return std::monostate{};
            }
        }

        // Note: Copy constructor, move constructor, assignment operators, and destructor
        // are all automatically generated by the compiler thanks to std::variant.
        // This eliminates 60+ lines of error-prone manual memory management!
    };
}
